name: Deploy to Custom Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to server
      env:
        #${{ secrets.SSH_PRIVATE_KEY }}  # Приватный ключ для доступа к серверу
        SSH_PRIVATE_KEY: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACCvUWELbG0tJfM8RSRqOBlsTDDPeuGRKPXBE1Fnvoek/wAAAKBPaBfvT2gX
            7wAAAAtzc2gtZWQyNTUxOQAAACCvUWELbG0tJfM8RSRqOBlsTDDPeuGRKPXBE1Fnvoek/w
            AAAECuO2lphA+LmGkxFY4dWbFc97Z+ZSeZvQ1Dmbmrh/OrXa9RYQtsbS0l8zxFJGo4GWxM
            MM964ZEo9cETUWe+h6T/AAAAGdCv0L3QtNC10LrRgSDQvNCw0YjQuNC90LABAgME
        #${{ secrets.SERVER_IP }}  # IP адрес вашего сервера
        SERVER_IP: 158.160.94.135
        # ${{ secrets.SERVER_USER }} # Пользователь для подключения к серверу
        SERVER_USER: maksmonster
        #${{ secrets.SERVER_DIR }}  # Директория на сервере для деплоя
        SERVER_DIR: SQL_tester
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

        # Копируем файлы на сервер
        rsync -avz --delete --exclude='.git' --exclude='.venv' ./ $SERVER_USER@$SERVER_IP:$SERVER_DIR

        # Запускаем приложение на сервере
        ssh $SERVER_USER@$SERVER_IP "cd $SERVER_DIR && source .venv/bin/activate && python main.py"